# Application Configuration

# Server settings
server:
  port: 8080
  context-path: /api

# Application settings
application:
  name: CI/DevOps Project
  version: 1.0.0
  environment: ${APP_ENV:development}
  
# Logging configuration
logging:
  level:
    root: INFO
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log